import {
  Card,
  CardMedia,
  CardContent,
  Typography,
  CircularProgress,
  Container,
  Box,
} from "@mui/material";
import DateSelector from "../components/DateSelector";
import { useSelector } from "react-redux";

const Apod = ({ selectedDate, setSelectedDate }) => {
  const { apod, loading, aiAnalysis } = useSelector((state) => state.apod);

  return (
    <Container maxWidth="md" sx={{ mt: 6, mb: 6 }}>
      <Box
        sx={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          mb: 3,
          flexDirection: { xs: "column", sm: "row" },
          gap: 2,
        }}
      >
        <Typography variant="h4" fontWeight={600}>
          Astronomy Picture of the Day
        </Typography>

        <DateSelector
          label="Select Date"
          value={selectedDate}
          onChange={setSelectedDate}
        />
      </Box>

      {loading || !apod ? (
        <Box textAlign="center" mt={8}>
          <CircularProgress color="primary" />
        </Box>
      ) : (
        <Card sx={{ boxShadow: 3, borderRadius: 2 }}>
          <Typography variant="h6" gutterBottom sx={{ p: 2 }}>
            {apod.title}
          </Typography>
          <CardMedia
            component="img"
            image={apod.url}
            alt={apod.title}
            sx={{
              height: { xs: 240, sm: 400 },
              objectFit: "cover",
              borderTopLeftRadius: 8,
              borderTopRightRadius: 8,
            }}
          />
          <CardContent>
            <Typography variant="body2" color="text.secondary">
              {apod.explanation}
            </Typography>
            <Box mt={4}>
              <Typography variant="subtitle1">
                <strong>Mood:</strong>{" "}
                <Box component="span" fontWeight={600} color="secondary.main">
                  {aiAnalysis?.mood || "N/A"}
                </Box>
              </Typography>
              <Typography variant="subtitle1">
                <strong>Style:</strong>{" "}
                <Box component="span" fontWeight={600} color="secondary.main">
                  {aiAnalysis?.style || "N/A"}
                </Box>
              </Typography>
              <Typography
                variant="caption"
                color="text.secondary"
                sx={{ mt: 1.5, display: "block", fontStyle: "italic" }}
              >
                The mood, style, and star colors below are generated by OpenAI
                based on the selected APOD image. Watch how the starfield
                background changes its colors to match each new picture when you
                select a different date!
              </Typography>
            </Box>
          </CardContent>
        </Card>
      )}
    </Container>
  );
};

export default Apod;
